stages:

- stage: BuildServices

  pool:
    vmImage: ubuntu-latest

  jobs:
  - job: BuildDocker_SalesBookLB
    displayName: Build Docker Image for SalesBookLB app

    steps:
    - task: Docker@2
      inputs:
        command: 'buildAndPush'
        Dockerfile: '**/SalesBook.LB/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest

