stages:

- stage: BuildServices

  pool:
    vmImage: ubuntu-latest

  jobs:
  - job: BuildDocker_SalesBookLB
    displayName: Build Docker Image for SalesBookLB app

    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'ferokbrelok95SvcConnection'
        repository: 'SalesBookLB'
        command: 'buildAndPush'
        Dockerfile: '**/SalesBook.LB/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest
    

  - job: BuildDocker_SalesBookWEB
    displayName: Build Docker Image for SalesBookWEB app
    steps:

    - task: Docker@2
      inputs:
        containerRegistry: 'ferokbrelok95SvcConnection'
        repository: 'SalesBookWEB'
        command: 'buildAndPush'
        Dockerfile: '**/SalesBook.WEB/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest

- stage: DeployAKS

  pool:
    vmImage: ubuntu-latest
  
  jobs:
  - job: DeploytoAKS
    displayName: Deploy to AKS
    
    steps:

    - task: KubernetesManifest@1
      inputs:
        action: 'deploy'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: 'dawid95-aksSvcConnection'
        manifests: '**/AKS/deployment.yaml'


- stage: changeTMconf
    
  pool: 
    vmImage: ubuntu-latest
    
  jobs:
  - job: increasTrafficManager0
    displayName: increasTrafficManager0
    steps:
    - script: echo "Deploying to development environment..."
      displayName: 'Deploy to Dev'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure for Students(ab44f02d-125d-43bd-a799-a38199c84012)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az network traffic-manager endpoint update --resource-group dawidtfstaterg --profile-name mytraficmanager --name e1-apache --weight 100 --type azureEndpoints
          az network traffic-manager endpoint update --resource-group dawidtfstaterg --profile-name mytraficmanager --name e2-nginx --weight 50 --type azureEndpoints
        useGlobalConfig: true
  - job: waitForNext
    displayName: waitForNext
    dependsOn: increasTrafficManager0
    pool: server
    steps:
    - task: Delay@1
      inputs:
        delayForMinutes: '1'  # Adjust the delay time as needed
  - job: increasTrafficManager1
    dependsOn: waitForNext
    displayName: increasTrafficManager1
    steps:
    - script: echo "Deploying to development environment..."
      displayName: 'Deploy to Dev'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure for Students(ab44f02d-125d-43bd-a799-a38199c84012)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az network traffic-manager endpoint update --resource-group dawidtfstaterg --profile-name mytraficmanager --name e1-apache --weight 100 --type azureEndpoints
          az network traffic-manager endpoint update --resource-group dawidtfstaterg --profile-name mytraficmanager --name e2-nginx --weight 100 --type azureEndpoints
        useGlobalConfig: true
  - job: waitForNext1
    pool: server
    displayName: waitForNext1
    dependsOn: increasTrafficManager1
    steps:
    - task: Delay@1
      inputs:
        delayForMinutes: '1'  # Adjust the delay time as needed
  - job: increasTrafficManager2
    displayName: increasTrafficManager2
    dependsOn: waitForNext1
    steps:
    - script: echo "Deploying to development environment..."
      displayName: 'Deploy to Dev'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure for Students(ab44f02d-125d-43bd-a799-a38199c84012)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az network traffic-manager endpoint update --resource-group dawidtfstaterg --profile-name mytraficmanager --name e1-apache --weight 100 --type azureEndpoints
          az network traffic-manager endpoint update --resource-group dawidtfstaterg --profile-name mytraficmanager --name e2-nginx --weight 200 --type azureEndpoints
        useGlobalConfig: true
  - job: waitForNext2
    pool: server
    displayName: waitForNext2
    dependsOn: increasTrafficManager2
    steps:
    - task: Delay@1
      inputs:
        delayForMinutes: '1'  # Adjust the delay time as needed
  - job: increasTrafficManager3
    displayName: increasTrafficManager3
    dependsOn: waitForNext2
    steps:
    - script: echo "Deploying to development environment..."
      displayName: 'Deploy to Dev'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure for Students(ab44f02d-125d-43bd-a799-a38199c84012)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az network traffic-manager endpoint update --resource-group dawidtfstaterg --profile-name mytraficmanager --name e1-apache --weight 50 --type azureEndpoints
          az network traffic-manager endpoint update --resource-group dawidtfstaterg --profile-name mytraficmanager --name e2-nginx --weight 900 --type azureEndpoints
        useGlobalConfig: true